/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer_desk.glb -T 
Files: computer_desk.glb [52.6MB] > F:\Web Development\Frontend React\portfolio_site\public\models\computer_desk-transformed.glb [2.03MB] (96%)
Author: CR!STALLL (https://sketchfab.com/CR1STALLL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-ff0674f66e11462e8b3417dee2b58ac9
Title: Computer Desk
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Computer(props) {
  const { nodes, materials } = useGLTF("/models/computer_desk-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk_Desk_0.geometry}
        material={materials.Desk}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book01_Book01_0.geometry}
        material={materials.Book01}
        position={[-0.473, 1, 0.024]}
        rotation={[0, 0.621, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book02_Book02_0.geometry}
        material={materials.Book02}
        position={[-0.509, 0.974, 0.004]}
        rotation={[0, 0.409, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Chair_0.geometry}
        material={materials.Chair}
        position={[0.002, 0, 0.699]}
        rotation={[-1.541, 0.021, 2.192]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Computer_Computer_0.geometry}
        material={materials.Computer}
        position={[0.869, 0.112, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cup_Cup_0.geometry}
        material={materials.material}
        position={[-0.225, 0.974, 0.065]}
        rotation={[Math.PI, -0.68, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DeskLamp_DeskLamp_0.geometry}
        material={materials.DeskLamp}
        position={[-0.005, 0.975, -0.045]}
        rotation={[0, 0.469, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DeskLamp_Alpha_0.geometry}
        material={materials.Alpha}
        position={[-0.005, 0.975, -0.045]}
        rotation={[0, 0.469, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard_Keyboard_0.geometry}
        material={materials.Keyboard}
        position={[0.333, 0.975, 0.235]}
        rotation={[-Math.PI / 2, 0, -0.459]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Loudspeaker01_Loudspeaker01_0.geometry}
        material={materials.Loudspeaker01}
        position={[0.194, 0.975, -0.156]}
        rotation={[-Math.PI / 2, 0, -0.225]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Loudspeaker02_Loudspeaker02_0.geometry}
        material={materials.Loudspeaker02}
        position={[0.853, 0.975, 0.175]}
        rotation={[-Math.PI / 2, 0, -0.718]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor_Monitor_0.geometry}
        material={materials.Monitor}
        position={[0.548, 0.975, -0.029]}
        rotation={[0, -0.445, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse_Mouse_0.geometry}
        material={materials.Mouse}
        position={[0.704, 0.976, 0.367]}
        rotation={[0, 0.172, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StationeryCup_StationeryCup_0.geometry}
        material={materials.StationeryCup}
        position={[-0.218, 0.974, -0.142]}
        rotation={[Math.PI, -1.03, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/models/computer_desk-transformed.glb");
